CREATE TABLE Centres (
  IdCentre BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  Name VARCHAR(255) NOT NULL
);

CREATE TABLE Persons (
  IdPerson BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  Lastname VARCHAR(255) NOT NULL,
  Firstname VARCHAR(255) NOT NULL 
);

CREATE TABLE Schedules (
  IdSchedule BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  ScheduleDate DATE NOT NULL,
  CentreId BIGINT NOT NULL,
  FOREIGN KEY (CentreId) REFERENCES Centres(IdCentre), 
  PersonId BIGINT NOT NULL,
  FOREIGN KEY (PersonId) REFERENCES Persons(IdPerson)
);